www/src/Entity/Student.php
<?php

namespace App\Entity;

use App\Entity\Calendar;
use App\Entity\PathProject;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\StudentRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=StudentRepository::class)
 * @ORM\Table(name="student", indexes={@ORM\Index(columns={"firstname", "lastname", "email"}, flags={"fulltext"})})
 */
class Student
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups("post:read")
     * @Groups("post:mail")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("post:read")
     * @Groups("post:mail")
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("post:read")
     * @Groups("post:mail")
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255)
     *  @Groups("post:mail")
     */
    private $email;

    /**
     * @ORM\Column(type="integer")
     *  @Groups("post:mail")
     */
    private $studentProgress;

    /**
     * @ORM\ManyToOne(targetEntity=Path::class, inversedBy="students")
     * @Groups("post:read")
     * @Groups("post:mail")
     */
    private $Path;

    /**
     * @ORM\ManyToOne(targetEntity=PathProject::class, inversedBy="students")
     * @Groups("post:mail")
     */
    private $project;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @Groups("post:mail")
     */
    private $lastAppointment;

    /**
     * @ORM\OneToMany(targetEntity=Calendar::class, mappedBy="student")
     * @Groups("post:mail")
     */
    private $calendars;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @Groups("post:mail")
     */
    private $nextAppointment;

    public function __construct()
    {
        $this->calendars = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getStudentProgress(): ?int
    {
        return $this->studentProgress;
    }

    public function setStudentProgress(int $studentProgress): self
    {
        $this->studentProgress = $studentProgress;

        return $this;
    }

    public function getPath(): ?Path
    {
        return $this->Path;
    }

    public function setPath(?Path $Path): self
    {
        $this->Path = $Path;

        return $this;
    }

    public function getProject(): ?PathProject
    {
        return $this->project;
    }

    public function setProject(?PathProject $project): self
    {
        $this->project = $project;

        return $this;
    }

    public function getLastAppointment(): ?\DateTimeInterface
    {
        return $this->lastAppointment;
    }

    public function setLastAppointment(?\DateTimeInterface $lastAppointment): self
    {
        $this->lastAppointment = $lastAppointment;

        return $this;
    }

    public function getNextAppointment(): ?\DateTimeInterface
    {
        return $this->nextAppointment;
    }

    public function setNextAppointment(\DateTimeInterface $nextAppointment): self
    {
        $this->nextAppointment = $nextAppointment;

        return $this;
    }

    public function __toString()
    {
        return $this->email . ' | ' . $this->firstname . ' ' . $this->lastname;
    }

    /**
     * @return Collection|Calendar[]
     */
    public function getCalendars(): Collection
    {
        return $this->calendars;
    }

    public function addCalendar(Calendar $calendar): self
    {
        if (!$this->calendars->contains($calendar)) {
            $this->calendars[] = $calendar;
            $calendar->setStudent($this);
        }

        return $this;
    }

    public function removeCalendar(Calendar $calendar): self
    {
        if ($this->calendars->removeElement($calendar)) {
            // set the owning side to null (unless already changed)
            if ($calendar->getStudent() === $this) {
                $calendar->setStudent(null);
            }
        }

        return $this;
    }
}

www/src/Form/SendMailType.php
<?php

namespace App\Form;

use App\Entity\Student;
use App\Entity\EmailTemplate;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class SendMailType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        $builder
            ->add('email', EntityType::class, [
                'class' => Student::class,
            ])
            ->add('mail_template', EntityType::class, [
                'class' => EmailTemplate::class,
                'required' => true,
                'mapped' => false,
                'attr' => [
                    'placeholder' => 'Subject ...',
                    'onchange' => 'singleSelectChangeValue()',
                ]
            ])
            ->add('content', TextareaType::class, [
                'required' => true,
                'mapped' => false,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            // Configure your form options here
        ]);
    }
}

www/src/Controller/SendMailController.php
<?php

namespace App\Controller;

use App\Entity\EmailTemplate;
use Twig\Environment;
use App\Entity\Student;
use App\Form\EmailTemplateType;
use App\Form\SendMailType;
use App\Form\SendBasicMailType;
use App\Service\SendMailService;
use App\Repository\PathRepository;
use App\Repository\MentorRepository;
use App\Repository\CalendarRepository;
use App\Repository\PathProjectRepository;
use App\Repository\EmailTemplateRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\SerializerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class SendMailController extends AbstractController
{

    private $entityManager;

    function __construct(EntityManagerInterface $entitymanager)
    {
        $this->entityManager = $entitymanager;
    }


    /**
     * @Route("/sendmail", name="send_mail")
     */
    public function index(Request $request, SerializerInterface $serializer, MentorRepository $mentor, SendMailService $mailer, CalendarRepository $calendar, Environment $twig): Response
    {

        // SEND BASIC MAIL WITH SYMFONY MAILLER
        $sendbasicmail = $this->createForm(SendBasicMailType::class);
        $sendbasicmail->handleRequest($request);

        if ($sendbasicmail->isSubmitted() && $sendbasicmail->isValid()) {

            //GET STUDENT EMAIL, SUBJECT AND CONTENT FOR BASIC EMAIL
            $studentemail = $sendbasicmail->get('email')->getData()->getEmail();
            $mailsubject = $sendbasicmail->get('subject')->getData();
            $mailcontent = $sendbasicmail->get('content')->getData();
            //GET MENTOR DATA
            $mentor = $mentor->findAll()[0];

            //SEND MAIL
            $mailer->send($studentemail, $mentor->getEmail(), $mailsubject,  ['content' => $mailcontent]);
        }

        // SEND TEMPLATE EMAIL WITH SYMFONY MAILLER
        $sendmail = $this->createForm(SendMailType::class);
        $sendmail->handleRequest($request);

        // VERIF FORM IS SUBMITTED AND IS VALID
        if ($sendmail->isSubmitted() && $sendmail->isValid()) {

            //GET STUDENT DATA
            $studentData = $sendmail->get('email')->getData();
            $json = $serializer->serialize($studentData, 'json', ['groups' => 'post:mail']);
            $student = json_decode($json);
            //GET MENTOR DATA
            $mentor = $mentor->findAll()[0];

            //GET STUDENT EMAIL, MAIL SUBJECT AND MAIL CONTENT FOR SEND EMAIL
            $studentemail = $studentData->getEmail();
            $mailsubject = $sendmail->get('mail_template')->getData()->getName();
            $mailcontent = html_entity_decode($sendmail->get('content')->getData());

            //GENERATE TEMPLATE FOR SENDING MAIL (IMPORTANT)
            $template = $this->get('twig')->createTemplate($mailcontent);
            $mailcontent = $twig->render($template, [
                'mentor' => $mentor,
                'student' => $student,
            ]);

            //SEND MAIL
            $mailer->send($studentemail, $mentor->getEmail(), $mailsubject,  ['content' => $mailcontent, 'mentor' => $mentor]);
        }

        return $this->render('send_mail/index.html.twig', [
            'sendbasicmail' => $sendbasicmail->createView(),
            'sendmail' => $sendmail->createView(),
        ]);
    }

    /**
     * @Route("/sendmail/all/template", name="all_template")
     */
    public function allTemplate(EmailTemplateRepository $emailtemplate)
    {
        $emailtemplate = $emailtemplate->findBy(array(), array('id' => 'ASC'), 8, 0);

        return $this->render('send_mail/all_template.html.twig', [
            'templates' => $emailtemplate
        ]);
    }

    /**
     * @Route("/sendmail/add/template", name="add_template")
     */
    public function addTemplate(Request $request)
    {
        $form = $this->createForm(EmailTemplateType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $template = $form->getData();

            $this->entityManager->persist($template);
            $this->entityManager->flush();

            $this->addFlash('success', 'Your New template is add !');
        }

        return $this->render('send_mail/add_template.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/sendmail/edit/template/{id}", name="edit_template")
     */
    public function editTemplate(Request $request, int $id, EmailTemplateRepository $emailtemplate)
    {

        $emailtemplate = $emailtemplate->findOneBy(['id' => $id]);

        $form = $this->createForm(EmailTemplateType::class, $emailtemplate);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $template = $form->getData();

            $this->entityManager->persist($template);
            $this->entityManager->flush();

            $this->addFlash('success', 'Your New template is edited !');
            return $this->redirectToRoute('all_template');
        }

        return $this->render('send_mail/edit_template.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/sendmail/remove/template/{id}", name="remove_template")
     */
    public function removeTemplate(int $id, EmailTemplateRepository $emailtemplate)
    {
        $emailtemplate = $emailtemplate->findOneBy(['id' => $id]);

        if (empty($emailtemplate)) {
            $this->addFlash('error', 'Your template is not removed !');
            return $this->redirectToRoute('all_template');
        }

        $this->entityManager->remove($emailtemplate);
        $this->entityManager->flush();
        $this->addFlash('success', 'Your email template is removed !');
        return $this->redirectToRoute('all_template');
    }

    /**
     * @Route("/sendmail/ajax/{id}", name="send_mail_ajax")
     */
    public function getSendMailWithAjax(SerializerInterface $serializer, EmailTemplateRepository $repository, int $id)
    {
        $template = $repository->findBy(['id' => $id]);
        $json = $serializer->serialize($template, 'json');

        $response = new Response($json, 200, [
            "Content-Type" => "application/json"
        ]);

        return  $response;
    }
}

www/templates/send_mail/add_template.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello SendMailController!
{% endblock %}

{% block content %}
	<section class="mt-5">
		<div class="section__content section__content--p30">
			<div class="container-fluid">
				<div class="row">
					<div
						class="col-xl-12">
						<!-- USER DATA-->
						<div class="user-data m-b-40">
							<h3 class="title-3 m-b-30">
								<i class="fas fa-user-graduate"></i>Add new Template Email</h3>
							<div class="col-lg-12">
								<div class="card">
									<div class="card-header">
										<strong>Template</strong>
									</div>
									<div class="card-body card-block">


										{{form_start(form)}}
										<div class="row form-group">
											<div class="col-12 col-md-12">
												{{ form_widget(form) }}
											</div>
										</div>
										<div class="row form-group">
											<div class="col-12 col-md-12">
												<h4>Email Options</h4>
												<div class="mt-2 d-flex flex-row justify-content-around">
													<div>
														<ul>
															<li>{{ '{{ student.id }}' }}</li>
															<li>{{ '{{ student.firstname }}' }}</li>
															<li>{{ '{{ student.lastname }}' }}</li>
															<li>{{ '{{ student.email }}' }}</li>
															<li>{{ '{{ student.path.name }}' }}</li>
															<li>{{ '{{ student.path.time }}' }}</li>
														</ul>
													</div>
													<div>
														<ul>
															<li>{{ '{{ student.project.name }}' }}</li>
															<li>{{ '{{ student.project.link }}' }}</li>
															<li>{{ '{{ student.project.time }}' }}</li>
															<li>{{ '{{ student.studentprogress }}' }}</li>
															<li>{{ '{{ student.lastAppointment }}' }}</li>
															<li>{{ '{{ student.nextAppointment }}' }}</li>
														</ul>
													</div>
													<div>
														<ul>
															<li>
																<div>{{ '{{ mentor.firstname }}' }}</div>
															</li>
															<li>
																<div>{{ '{{ mentor.lastname }}' }}</div>
															</li>
															<li>
																<div>{{ '{{ mentor.email }}' }}</div>
															</li>
															<li>
																<div>{{ '{{ mentor.visiolink }}' }}</div>
															</li>
															<li>
																<div>{{ '{{ mentor.discordlink }}' }}</div>
															</li>
															<li>
																<div>{{ '{{ mentor.workplacelink }}' }}</div>
															</li>
														</ul>
													</div>
												</div>
											</div>
										</div>
									</div>
									<div class="card-footer">
										<button type="submit" class="btn btn-outline-success">
											<i class="fas fa-plus"></i>&nbsp; Add Mail Template</button>
										<button type="reset" class="btn btn-outline-danger">
											<i class="fas fa-ban"></i>&nbsp; Reset</button>
									</div>
									{{form_end(form)}}
								</div>
							</div>

						</div>
						<!-- END USER DATA-->
					</div>
				</div>
			</div>
		</div>

	</section>
{% endblock %}

{% block javascript %}
	<script src="{{asset('/vendor/ckeditor/ckeditor.js')}}"></script>
	<script src="{{asset('/js/sendmail.js')}}"></script>
	<script>
		CKEDITOR.replace('email_template_content', {height: 300});
	</script>
{% endblock %}

www/templates/send_mail/all_template.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello SendMailController!
{% endblock %}

{% block content %}
	<section class="mt-5">
		<div class="section__content section__content--p30">
			<div class="container-fluid">
				<div class="row">
					<div
						class="col-xl-12">
						<!-- USER DATA-->
						<div class="user-data m-b-40">
							<h3 class="title-3 m-b-30">
								<i class="fas fa-user-graduate"></i>Add new Template Email</h3>
							<div class="col-lg-12">
								<div class="card">
									<div class="card-header">
										<strong>Template</strong>
									</div>
									<div class="table-responsive table-data">
										<table class="table">
											<thead>
												<tr>
													<td>name</td>
													<td class="text-center">template content</td>
												</tr>
											</thead>
											<tbody>
												{% for template in templates %}

													<tr>
														<td>
															<p>{{template.name}}</p>
														</td>
														<td class="text-center">
															<button type="button" class="btn btn-success mb-1" data-toggle="modal" data-target="#{{template.id}}">

																<i class="fas fa-file"></i>&nbsp; Content
															</button>
														</td>
														<td>
															<div class="table-data-feature">
																<a href="/sendmail/edit/template/{{template.id}}">
																	<button class="item" data-toggle="tooltip" data-placement="top" title="" data-original-title="Edit Template">
																		<i class="zmdi zmdi-edit"></i>
																	</button>
																</a>
																<a href="/sendmail/remove/template/{{template.id}}">
																	<button class="item ml-1" data-toggle="tooltip" data-placement="top" title="" data-original-title="Remove Template">
																		<i class="zmdi zmdi-delete"></i>
																	</button>
																</a>
															</div>
														</td>
													</tr>
												{% endfor %}
											</tbody>
										</table>
									</div>
									<div class="user-data__footer">
										<a>
											<button class="au-btn au-btn-load mr-1">load more</button>
										</a>
									</div>


								</div>
							</div>

						</div>
						<!-- END USER DATA-->
					</div>
				</div>
			</div>
		</div>

	</section>


	{% for template in templates %}

		<div class="modal fade" id="{{template.id}}" tabindex="-1" role="dialog" aria-labelledby="largeModalLabel" aria-hidden="true">
			<div class="modal-dialog modal-lg" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title" id="largeModalLabel">Email template</h5>
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">×</span>
						</button>
					</div>
					<div class="modal-body">
						<p>
							{{template.content|raw}}
						</p>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-secondary" data-dismiss="modal">close</button>
					</div>
				</div>
			</div>
		</div>


	{% endfor %}

{% endblock %}

{% block javascript %}
	<script src="{{asset('/vendor/ckeditor/ckeditor.js')}}"></script>
	<script src="{{asset('/js/sendmail.js')}}"></script>
	<script>
		CKEDITOR.replace('email_template_content', {height: 300});
	</script>
{% endblock %}

www/templates/send_mail/edit_template.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello SendMailController!
{% endblock %}

{% block content %}
	<section class="mt-5">
		<div class="section__content section__content--p30">
			<div class="container-fluid">
				<div class="row">
					<div
						class="col-xl-12">
						<!-- USER DATA-->
						<div class="user-data m-b-40">
							<h3 class="title-3 m-b-30">
								<i class="fas fa-user-graduate"></i>Add new Template Email</h3>
							<div class="col-lg-12">
								<div class="card">
									<div class="card-header">
										<strong>Template</strong>
									</div>
									<div class="card-body card-block">


										{{form_start(form)}}
										<div class="row form-group">
											<div class="col-12 col-md-12">
												{{ form_widget(form) }}
											</div>
										</div>
										<div class="row form-group">
											<div class="col-12 col-md-12">
												<h4>Email Options</h4>
												<div class="mt-2 d-flex flex-row justify-content-around">
													<div>
														<ul>
															<li>{{ '{{ student.id }}' }}</li>
															<li>{{ '{{ student.firstname }}' }}</li>
															<li>{{ '{{ student.lastname }}' }}</li>
															<li>{{ '{{ student.email }}' }}</li>
															<li>{{ '{{ student.path.name }}' }}</li>
															<li>{{ '{{ student.path.time }}' }}</li>
														</ul>
													</div>
													<div>
														<ul>
															<li>{{ '{{ student.project.name }}' }}</li>
															<li>{{ '{{ student.project.link }}' }}</li>
															<li>{{ '{{ student.project.time }}' }}</li>
															<li>{{ '{{ student.studentprogress }}' }}</li>
															<li>{{ '{{ student.lastAppointment }}' }}</li>
															<li>{{ '{{ student.nextAppointment }}' }}</li>
														</ul>
													</div>
													<div>
														<ul>
															<li>
																<div>{{ '{{ mentor.firstname }}' }}</div>
															</li>
															<li>
																<div>{{ '{{ mentor.lastname }}' }}</div>
															</li>
															<li>
																<div>{{ '{{ mentor.email }}' }}</div>
															</li>
															<li>
																<div>{{ '{{ mentor.visiolink }}' }}</div>
															</li>
															<li>
																<div>{{ '{{ mentor.discordlink }}' }}</div>
															</li>
															<li>
																<div>{{ '{{ mentor.workplacelink }}' }}</div>
															</li>
														</ul>
													</div>
												</div>
											</div>
										</div>
									</div>
									<div class="card-footer">
										<button type="submit" class="btn btn-outline-success">
											<i class="fas fa-edit"></i>&nbsp; Edit Template</button>
										<button type="reset" class="btn btn-outline-danger">
											<i class="fas fa-ban"></i>&nbsp; Reset</button>
									</div>
									{{form_end(form)}}
								</div>
							</div>

						</div>
						<!-- END USER DATA-->
					</div>
				</div>
			</div>
		</div>

	</section>
{% endblock %}

{% block javascript %}
	<script src="{{asset('/vendor/ckeditor/ckeditor.js')}}"></script>
	<script src="{{asset('/js/sendmail.js')}}"></script>
	<script>
		CKEDITOR.replace('email_template_content', {height: 300});
	</script>
{% endblock %}

www/templates/send_mail/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello SendMailController!
{% endblock %}

{% block content %}
	<section class="mt-5">
		<div class="section__content section__content--p30">
			<div class="container-fluid">
				<div class="row">
					<div
						class="col-xl-12">
						<!-- USER DATA-->
						<div class="user-data m-b-40">
							<h3 class="title-3 m-b-30">
								<i class="fas fa-user-graduate"></i>Send Mail</h3>
							<div class="col-lg-12">
								<div class="card">
									<div class="card-header">
										<strong>Auto Mailing system</strong>
									</div>
									<div class="card-body card-block">


										{{form_start(sendmail)}}
										<div class="row form-group">
											<div class="col col-md-12">
												<div class="input-group">
													{{ form_widget(sendmail.email) }}
													<div class="input-group-addon">
														<i class="fas fa-user-graduate"></i>
													</div>
												</div>
											</div>
										</div>
										<div class="row form-group">
											<div class="col-12 col-md-12">
												{{ form_widget(sendmail.mail_template) }}
											</div>
										</div>
										<div class="row form-group">
											<div class="col-12 col-md-12">
												<h5 class="text-center">Template Render</h5>
											</div>
										</div>
										<div class="row form-group">
											<div class="col-12 col-md-12">
												{{ form_widget(sendmail.content) }}
											</div>
										</div>
										<div class="row form-group">
											<div class="col-12 col-md-12">
												<h4>Email Options</h4>
												<div class="mt-2 d-flex flex-row justify-content-around">
													<div>
														<ul>
															<li>{{ '{{ student.id }}' }}</li>
															<li>{{ '{{ student.firstname }}' }}</li>
															<li>{{ '{{ student.lastname }}' }}</li>
															<li>{{ '{{ student.email }}' }}</li>
															<li>{{ '{{ student.path.name }}' }}</li>
															<li>{{ '{{ student.path.time }}' }}</li>
														</ul>
													</div>
													<div>
														<ul>
															<li>{{ '{{ student.project.name }}' }}</li>
															<li>{{ '{{ student.project.link }}' }}</li>
															<li>{{ '{{ student.project.time }}' }}</li>
															<li>{{ '{{ student.studentprogress }}' }}</li>
															<li>{{ '{{ student.lastAppointment }}' }}</li>
															<li>{{ '{{ student.nextAppointment }}' }}</li>
														</ul>
													</div>
													<div>
														<ul>
															<li>
																<div>{{ '{{ mentor.firstname }}' }}</div>
															</li>
															<li>
																<div>{{ '{{ mentor.lastname }}' }}</div>
															</li>
															<li>
																<div>{{ '{{ mentor.email }}' }}</div>
															</li>
															<li>
																<div>{{ '{{ mentor.visiolink }}' }}</div>
															</li>
															<li>
																<div>{{ '{{ mentor.discordlink }}' }}</div>
															</li>
															<li>
																<div>{{ '{{ mentor.workplacelink }}' }}</div>
															</li>
														</ul>
													</div>
												</div>
											</div>
										</div>
									</div>
									<div class="card-footer">
										<button type="submit" class="btn btn-outline-success">
											<i class="far fa-paper-plane"></i>&nbsp; Send Mail</button>
										<button type="reset" class="btn btn-outline-danger">
											<i class="fas fa-ban"></i>&nbsp; Reset</button>
									</div>
									{{form_end(sendmail)}}
								</div>
							</div>


							<div class="col-lg-12">
								<div class="card">
									<div class="card-header">
										<strong>Send Basic email</strong>
									</div>
									<div class="card-body card-block">
										{{form_start(sendbasicmail)}}
										<div class="row form-group">
											<div class="col col-md-12">
												<div class="input-group">
													{{ form_widget(sendbasicmail.email) }}
													<div class="input-group-addon">
														<i class="fas fa-user-graduate"></i>
													</div>
												</div>
											</div>
										</div>
										<div class="form-group">
											<div class="input-group">
												{{ form_widget(sendbasicmail.subject) }}
												<div class="input-group-addon">
													<i class="fa fa-asterisk"></i>
												</div>
											</div>
										</div>
										<div class="row form-group">
											<div class="col-12 col-md-12">
												<h5 class="text-center">Your email</h5>
											</div>
										</div>
										<div class="row form-group">
											<div class="col-12 col-md-12">
												{{ form_widget(sendbasicmail.content) }}
											</div>
										</div>

									</div>
									<div class="card-footer">
										<button type="submit" class="btn btn-outline-success">
											<i class="far fa-paper-plane"></i>&nbsp; Send Mail</button>
										<button type="reset" class="btn btn-outline-danger">
											<i class="fas fa-ban"></i>&nbsp; Reset</button>
									</div>
								</div>
								{{ form_end(sendbasicmail) }}
							</div>

						</div>
						<!-- END USER DATA-->
					</div>
				</div>
			</div>
		</div>

	</section>
{% endblock %}

{% block javascript %}
	<script src="{{asset('/vendor/ckeditor/ckeditor.js')}}"></script>
	<script src="{{asset('/js/sendmail.js')}}"></script>
	<script>
		CKEDITOR.replace('send_mail_content', {height: 300});
CKEDITOR.replace('send_basic_mail_content', {height: 300});
	</script>
{% endblock %}